shell_command:
  switch_on: "python3 /config/send_serial_cmd.py {{ name }} ON"
  switch_off: "python3 /config/send_serial_cmd.py {{ name }} OFF"

  dimmable_light_on: "python3 /config/send_serial_cmd.py {{ name }} ON"
  dimmable_light_off: "python3 /config/send_serial_cmd.py {{ name }} OFF"
  dimmable_light_level: "python3 /config/send_serial_cmd.py {{ name }} LEVEL {{ brightness }}"

switch:
  - platform: template
    switches:
      switch1:
        turn_on:
          - service: shell_command.switch_on
            data:
              name: switch1
        turn_off:
          - service: shell_command.switch_off
            data:
              name: switch1

light:
  - platform: template
    lights:
      light1:
        friendly_name: "light1"
        turn_on:
          - service: shell_command.dimmable_light_on
            data:
              name: dimmablelight1
        turn_off:
          - service: shell_command.dimmable_light_off
            data:
              name: dimmablelight1
        set_level:
          - service: shell_command.dimmable_light_level
            data:
              name: dimmablelight1
              brightness: "{{ (brightness * 1023 / 255) | int }}" #Convert the interval of 0-255 to 0-1023
